### ISSUE TITLE
slash_util.Bot.get_context() raising `TypeError` on custom class

### ISSUE THREAD

**Issue by Eleiber** [XuaTheGrate/slash_util#16]
Hi! I'm trying to migrate from discord.py 2.0 to slash_util, but in my class which I use to add an attribute to my context (and it works on 2.0) is raising a `TypeError: __init__() got an unexpected keyword argument 'prefix'`
This is my current code. The only things I've changed were `commands.Bot` to `slash_util.Bot` and `commands.Context` to `slash_util.Context`.
```python
class Noether(slash_util.Bot):
    async def get_context(self, message, *, cls=slash_util.Context):
        ctx = await super().get_context(message, cls=cls) 
        # ... more code
```
And this is the full traceback:
```python
Ignoring exception in on_message
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/discord/client.py", line 351, in _run_event
    await coro(*args, **kwargs)
  File "bot.py", line 404, in on_message
    await bot.process_commands(message)
  File "/usr/local/lib/python3.8/dist-packages/discord/ext/commands/bot.py", line 1030, in process_commands
    ctx = await self.get_context(message)
  File "bot.py", line 54, in get_context
    ctx = await super().get_context(message, cls=cls)
  File "/usr/local/lib/python3.8/dist-packages/discord/ext/commands/bot.py", line 935, in get_context
    ctx = cls(prefix=None, view=view, bot=self, message=message)
TypeError: __init__() got an unexpected keyword argument 'prefix'
```
I also tried and saw that changing `slash_util.Context` back to `commands.Context` makes it work, but that would be pointless since I could not use most of the features of the library.

**Comment by mysistersbrother** [comment]
This isn't a bug, d.py command handler is for message commands. Slash_util is for application commands. You do not need to do this nor did was this recommended. To fix this just don't do it.
